---
deployment:
  tasks:
    - "/bin/mkdir -p /home2/matchpo3/public_html/hr"
    - "/bin/cp -R /home2/matchpo3/repositories/IHRP/web/. /home2/matchpo3/public_html/hr/"
    - "/usr/local/bin/php /home2/matchpo3/public_html/hr/artisan config:cache"
    - "/usr/local/bin/php /home2/matchpo3/public_html/hr/artisan route:cache"
    - "/usr/local/bin/php /home2/matchpo3/public_html/hr/artisan view:cache"
