---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/matchpo3/public_html/hr
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R web/. $DEPLOYPATH/
    - /usr/local/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan route:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan view:cache
