---
deployment:
  tasks:
    - "/bin/mkdir -p /home2/rbjwhhmy/public_html/hr"
    - "/bin/cp -R /home2/rbjwhhmy/repositories/IHRP/web/. /home2/rbjwhhmy/public_html/hr/"
    - "/opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader --working-dir=/home2/rbjwhhmy/public_html/hr"
    - "/opt/cpanel/ea-php83/root/usr/bin/php /home2/rbjwhhmy/public_html/hr/artisan config:cache"
    - "/opt/cpanel/ea-php83/root/usr/bin/php /home2/rbjwhhmy/public_html/hr/artisan route:cache"
    - "/opt/cpanel/ea-php83/root/usr/bin/php /home2/rbjwhhmy/public_html/hr/artisan view:cache"
